<a href="https://colab.research.google.com/github/sig2nya/MachineLearning/blob/main/lib/numpy_tutor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
print(np.__version__)
print(np.__name__)

1.25.2
numpy


In [7]:
# 1. List
# 확장성에 유리, 수치 계산에 불리
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(type(list1))
print(list1 + list2)

<class 'list'>
[1, 2, 3, 4, 5, 6]


In [25]:
# 2. Array. List의 경우 다중 데이터 타입 수용 가능하나, Array의 경우 단일 데이터 타입만 수용 가능. 성능 면에서는 np.array가 훨 빠름(대규모 데이터)
array = np.array([1, 2, 3])
print('array type : ', type(array))
print('-' * 10)
print('array')
print(array)
print('-' * 10)
print('array dimension : ', array.ndim) # Array's Dimention
print('array shape : ', array.shape)

array2 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
print('-' * 10)
print('array2')
print(array2)
print('-' * 10)
print('array2 dimension : ', array2.ndim)
print('array2 dtype : ', array2.dtype)

array_float = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print('array_float dtype : ', array_float.dtype)
print('array_float size : ', array_float.size)

array = np.array([[1, 2, 3], [4, 5, 6]])
print('array transpose : \n', array.T)

array type :  <class 'numpy.ndarray'>
----------
array
[1 2 3]
----------
array dimension :  1
array shape :  (3,)
----------
array2
[[1 2 3]
 [4 5 6]]
----------
array2 dimension :  2
array2 dtype :  int64
array_float dtype :  float64
array_float size :  6
array transpose : 
 [[1 4]
 [2 5]
 [3 6]]


In [39]:
# 3. arange() range와 유사한 함수. 수열을 생성하기 위해 주로 사용. 숫자 시퀀스 생성
print('Ch 1')
a = np.arange(10)
print(a)

a = np.arange(2, 10)
print(a)

a = np.arange(1, 10, 2) # Step Setting
print(a)

# 4. linspace() 수의 범위를 균일하게 나눌 때 사용
print('\n')
print('Ch 2')
b = np.linspace(1, 11, 10)
print(b)

Ch 1
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]


Ch 2
[ 1.          2.11111111  3.22222222  4.33333333  5.44444444  6.55555556
  7.66666667  8.77777778  9.88888889 11.        ]


In [44]:
# 4. zeros, one, full
zeros = np.zeros(shape=(3, 5))
print(zeros)

ones = np.ones(shape=(3, 5))
print(ones)

full = np.full(shape=(3, 5), fill_value=5)
print(full)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [47]:
# 5. eye() Identical matrix 생성.(단위행렬)
a = np.eye(5)
print(a)
print(type(a))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [53]:
# 6. randn() 난수 생성
a = np.random.randn(5)
print(a)

print('[3 * 5 array]')
a = np.random.randn(3, 5)
print(a)

[-1.78483799  0.01215034 -0.39900439 -0.04409165  0.96953828]
[3 * 5 array]
[[ 0.81658627 -0.90924451 -1.70828931  1.20141249 -0.16370741]
 [-1.73423196  0.54248252 -0.38349281  1.23285766  1.75216115]
 [-1.28017358 -0.11588327  0.63709131 -0.26153103  1.45524248]]


In [29]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)
print(arr[2])
print(arr[-1])
# print(arr[6]) # Error!!!

(5,)
3
5


In [12]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12 ,13 ,14, 15]
])
print(arr.shape)
print(arr[2, 3])
print(arr[2][3])

(3, 5)
14
14


In [16]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[:2])
print(arr[-2:])

[1 2]
[4 5]


In [21]:
arr = np.array(
    [
     [1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13 ,14, 15]
     ]
)

print(arr[:, 1:3])
print(arr[:2, 1:3])

[[ 2  3]
 [ 7  8]
 [12 13]]
[[2 3]
 [7 8]]


In [28]:
arr = np.arange(15)
print(arr)
print(f'ndim : {arr.ndim}, shape : {arr.shape}')
print(arr.reshape(5, 3))
print(arr.reshape(5, -1))
print(arr.reshape(-1, 5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
ndim : 1, shape : (15,)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [31]:
x = np.array([[10, 20], [30, 40]])
y = np.array([[5, 6], [7, 8]])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x % y)
print(x // y)

[[15 26]
 [37 48]]
[[ 5 14]
 [23 32]]
[[ 50 120]
 [210 320]]
[[2.         3.33333333]
 [4.28571429 5.        ]]
[[0 2]
 [2 0]]
[[2 3]
 [4 5]]
