In [1]:
import numpy as np

In [2]:
arr1 = [1, 2, 3, 4, 5]
arr2 = np.array([1, 2, 3, 4, 5])

In [3]:
arr3 = np.array([[3, 4], [5, 6]])

In [4]:
arr4 = np.array([[1, 2], [3, 4]])

In [6]:
print(arr3)
print(arr4)

[[3 4]
 [5 6]]
[[1 2]
 [3 4]]


In [7]:
print(arr3 + arr4)

[[ 4  6]
 [ 8 10]]


In [8]:
print(arr3 * arr4)

[[ 3  8]
 [15 24]]


In [10]:
arr5 = np.arange(10)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
print(arr5[0])

0


In [12]:
print(arr5[5])

5


In [13]:
print(arr5[3:9])

[3 4 5 6 7 8]


In [14]:
print(arr5[:])

[0 1 2 3 4 5 6 7 8 9]


In [18]:
arr6 = np.array([[1, 2, 3], [4 , 5, 6]])
print(arr6[0, 1])

2


In [20]:
print(arr6[0, :])

[1 2 3]


In [21]:
print(arr6[0, 0:2])

[1 2]
