Tensor
======
- 다차원 배열을 처리하기 위한 데이터 구조
- GPU를 사용하지 못하는 numpy의 문제 해결
- numpy와 같이 nd-array 연산 지원
- 3D 이상의 array는 tensor이다
- jupyter notebook에서 torch 환경을 구성하기 위해서는 추가 작업을 해주어야 한다. 구글링 해보자.

In [1]:
import torch

In [6]:
torch.cuda.is_available()

False

In [7]:
data = [[1, 2], [3, 4]]
t = torch.tensor(data)

In [8]:
print(t, t.dtype, t.shape)

tensor([[1, 2],
        [3, 4]]) torch.int64 torch.Size([2, 2])


In [9]:
t = torch.tensor([[1, 2], [3, 4]])
print(t, t.dtype, t.shape)

tensor([[1, 2],
        [3, 4]]) torch.int64 torch.Size([2, 2])


In [10]:
t_cpu = torch.tensor([[1, 2], [3, 4]], device='cpu')
t_gpu = torch.tensor([[1, 2], [3, 4]], device='cuda:0')

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [16]:
t_32 = torch.tensor([[1, 2], [3, 4]])
t_64 = torch.tensor([[1, 2], [3, 4]], dtype = torch.float64)
print(t_32)
print(t_64)

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [17]:
t = torch.arange(0, 10)
print(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [20]:
t = torch.zeros(3, 2)
print(t, t.shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) torch.Size([3, 2])


In [22]:
t = torch.ones(3, 2)
print(t, t.shape)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) torch.Size([3, 2])


In [24]:
t = t.to('cuda')
print(t)

AssertionError: Torch not compiled with CUDA enabled

In [32]:
t = torch.randn(3, 2)
print(t)

tensor([[-0.1670, -0.2608],
        [ 0.1586,  0.2788],
        [ 0.7104,  0.5466]])


In [30]:
t_data = t.data.tolist()
print(t_data)

[[0.10763287544250488, 0.7509221434593201], [0.037908196449279785, 0.9046823382377625], [0.28139692544937134, 0.12006419897079468]]


In [33]:
t = torch.rand(2, 3)
cpu = torch.device('cpu')
gpu = torch.device('cuda')

In [38]:
if torch.cuda.is_available():
    t_gpu = t.to(gpu)
    print('cuda is available')

In [40]:
t_gpu = t_gpu.to(cpu)
print(t_cpu)

NameError: name 't_gpu' is not defined

In [41]:
t = torch.ones(3, 2)
t = t.to('cuda')
print(t)

AssertionError: Torch not compiled with CUDA enabled

In [46]:
t = torch.rand(2, 3)
print(t)
t_ones = torch.ones_like(t)
t_zeros = torch.zeros_like(t)
print(t_ones, t_zeros)

tensor([[0.3669, 0.7403, 0.0333],
        [0.8606, 0.1945, 0.8025]])
tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [47]:
t = torch.tensor(data)

In [50]:
t_T = torch.Tensor([[1, 2, 3], [4, 5, 6]])
t_FT = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(t_T)
print(t_FT)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [52]:
t_T = t_T.type(dtype=torch.IntTensor)
print(t_T)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
