<a href="https://colab.research.google.com/github/sig2nya/MachineLearning/blob/main/kmooc/ch2/pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor
======
- 다차원 배열을 처리하기 위한 데이터 구조
- GPU를 사용하지 못하는 numpy의 문제 해결
- numpy와 같이 nd-array 연산 지원
- 3D 이상의 array는 tensor이다
- jupyter notebook에서 torch 환경을 구성하기 위해서는 추가 작업을 해주어야 한다. 구글링 해보자.

In [21]:
import torch

In [22]:
torch.cuda.is_available() 
# cuda는 Compute Unified Device Architecture의 약어이다. torch.cuda.is_available() 함수를 호출하면 GPU 사용 여부를 확인할 수 있다.

True

In [23]:
data = [[1, 2], [3, 4]]
t = torch.tensor(data)
# list인 data를 tensor type으로 변환

In [24]:
print(t, t.dtype, t.shape)
# t의 type tensor, data type - int, Size 확인

tensor([[1, 2],
        [3, 4]]) torch.int64 torch.Size([2, 2])


In [25]:
t = torch.tensor([[1, 2], [3, 4]])
print(t, t.dtype, t.shape)
# 마찬가지로 변수를 통해 tensor를 생성하는 것이 아닌 직접 list를 argument로 전달함으로써 tensor를 생성

tensor([[1, 2],
        [3, 4]]) torch.int64 torch.Size([2, 2])


In [26]:
t_cpu = torch.tensor([[1, 2], [3, 4]], device='cpu')
t_gpu = torch.tensor([[1, 2], [3, 4]], device='cuda:0')
# t_cpu는 cpu에 tensor를 생성하며 마찬가지로 t_gpu는 gpu에 tensor를 생성

In [27]:
t_32 = torch.tensor([[1, 2], [3, 4]])
t_64 = torch.tensor([[1, 2], [3, 4]], dtype = torch.float64)
print(t_32)
print(t_64)
# data type을 지정하여 tensor를 생성합니다.

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [28]:
t = torch.arange(0, 10) # 0 ~ 9까지의 수열을 tensor로 생성합니다
print(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [29]:
t = torch.zeros(3, 2) # tensor의 모든 요소를 0으로 초기화 하고 싶을 때 torch.zeros 함수를 사용합니다
print(t, t.shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) torch.Size([3, 2])


In [30]:
t = torch.ones(3, 2) # tensor의 모든 요소를 1로 초기화 하고 싶을 때 torch.ones 함수를 사용합니다
print(t, t.shape)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) torch.Size([3, 2])


In [31]:
t = t.to('cuda') # torch.Tensor.to 함수는 dtype이나 device를 변경할 때 사용합니다. 여기서, arg 값이 'cuda'이므로 device를 cuda로 변경한다는 뜻이고 GPU를 사용하겠다는 의미가 되겠습니다
print(t)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')


In [32]:
t = torch.randn(3, 2) # 평균이 0이고 표준편차가 1인 Gaussian 정규 분포를 사용하여 난수를 생성합니다
print(t)

tensor([[ 0.8679, -0.7035],
        [ 0.3697, -1.5165],
        [ 0.5381, -1.3826]])


In [33]:
t_data = t.data.tolist() # t에 존재하는 데이터를 list로 변환합니다.
print(t_data)

[[0.8678854703903198, -0.7034857869148254], [0.3696555495262146, -1.5164830684661865], [0.538088858127594, -1.3825727701187134]]


In [34]:
t = torch.rand(2, 3) # 0 ~ 1 사이의 수를 생성합니다
cpu = torch.device('cpu')
gpu = torch.device('cuda')

In [35]:
if torch.cuda.is_available():
    t_gpu = t.to(gpu)
    print('cuda is available') # 현재 GPU를 사용할 수 있는 상태이므로, 출력됩니다.

cuda is available


In [36]:
t_gpu = t_gpu.to(cpu) # t_gpu를 cpu를 사용하여 연산합니다
print(t_cpu)

tensor([[1, 2],
        [3, 4]])


In [37]:
t = torch.ones(3, 2) # 마찬가지로 3 * 2행의 tensor를 1로 초기화 수행합니다
t = t.to('cuda')
print(t)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')


In [38]:
t = torch.rand(2, 3)
print(t)
t_ones = torch.ones_like(t) # 입력한 tensor와 동일 tensor를 생성하는데, 1로 초기화 합니다
t_zeros = torch.zeros_like(t) # 마찬가지로 입력한 tensor와 동일 tensor를 생성하는데, 0으로 초기화 합니다다
print(t_ones, t_zeros)

tensor([[0.5555, 0.8419, 0.4961],
        [0.2826, 0.8133, 0.6046]])
tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [39]:
t = torch.tensor(data)

In [40]:
t_T = torch.Tensor([[1, 2, 3], [4, 5, 6]])
t_FT = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(t_T)
print(t_FT)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [41]:
t_T = t_T.type(dtype=torch.IntTensor)
print(t_T)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
