Numpy ndarray 개요
================

###### 1. ndarray : numpy의 N차원 배열 객체
###### - Python의 list와 가장 큰 차이점은, 하나의 data type만 넣을 수 있다.
###### - C의 array와 동일하다

In [6]:
import numpy as np

In [16]:
a = [1, 2, 3, 4, 5]
a_ndarr = np.array(a, int) # a array를 int type으로 선언

In [4]:
list1 = [1, 2, 3]
print('list type : ', type(list1))

list type :  <class 'list'>


In [9]:
array1 = np.array(list1)
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape)

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)


In [14]:
array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape)

array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)


In [15]:
array3 = np.array([[1, 2, 3]])
print('array3 type : ', type(array3))
print('array3 array 형태 : ', array3.shape)

array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)


In [20]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


In [17]:
c = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
c_ndarr = np.array(c, int)
print(c_ndarr.shape)
print(c_ndarr.dtype)

(3, 3)
int32


In [19]:
d = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
     [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
     [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
     [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]

d_ndarr = np.array(d, int)
print(d_ndarr.shape) #3rd order tensor
print(d_ndarr.ndim) #number of dimensions
print(d_ndarr.size) # 4 * 3 * 4

d_ndarr = np.array(d, dtype=np.int8)
print(d_ndarr.dtype) # int8

(4, 3, 4)
3
48
int8


ndarray의 데이터 타입
=================

In [24]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [25]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, " / ", array2.dtype)

['1' '2' 'test']  /  <U11


In [26]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, " / ", array3.dtype)

[1. 2. 3.]  /  float64


In [31]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, " / ", array_float.dtype)

[1. 2. 3.]  /  float64


In [32]:
array_int1 = array_float.astype('int32')
print(array_int1,  " / ", array_int1.dtype)

[1 2 3]  /  int32


In [33]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, " / ", array_int2.dtype)

[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeors, ones


In [36]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [38]:
zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [41]:
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape

In [42]:
array1 = np.arange(10)
print('array1 : \n', array1)

array1 : 
 [0 1 2 3 4 5 6 7 8 9]


In [43]:
array2 = array1.reshape(2, 5)
print('array2 : \n', array2) # 2차원 행렬로 변경

array2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [44]:
array3 = array1.reshape(5, 2)
print('array3 : \n', array3)

array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [45]:
array1.reshape(4, 3)
#불가능. 변환전 사이즈와 변환 후 사이즈가 같아야하는듯...

ValueError: cannot reshape array of size 10 into shape (4,3)

In [49]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
# -1  arg는 남은 배열의 길이와 남은 차원으로부터 알아서 지정하는 것을 의미
print('array2 is : \n', array2)
print('array2 shape : ', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 is : \n', array3)
print('array3 shape : ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 is : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array2 shape :  (2, 5)
array3 is : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3 shape :  (5, 2)


In [50]:
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [53]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d : \n', array3d.tolist())

array3d : 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [54]:
array5 = array3d.reshape(-1, 1)
print('array5 : \n', array5.tolist())
print('array5 shape : ', array5.shape)

array5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape :  (8, 1)


In [55]:
array6 = array1.reshape(-1, 1)
print('array6 : \n', array6.tolist())
print('array6 shape : ', array6.shape)

array6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape :  (8, 1)


In [56]:
array1d = array3d.reshape(-1,)
print(array1d)

[0 1 2 3 4 5 6 7]


### 선형대수 연산 - inner product / transpose matrix 구하기

* 행렬내적

In [57]:
A = np.array([[1, 2, 3],
             [4, 5, 6]
             ])
B = np.array([[7, 8],
             [9, 10],
             [11, 12]
             ])
dot_product = np.dot(A, B)
print('inner product result : \n', dot_product)

inner product result : 
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [65]:
A = np.array([[1, 2],
             [3, 4]
             ])
transpose_matrix = np.transpose(A)
print('A의 전치 행렬 : \n', transpose_matrix)

A의 전치 행렬 : 
 [[1 3]
 [2 4]]
